import React from 'react';
import QueryProvider from '@/provider/QueryProvider';
import { pretendard } from '@/utils/fonts';
import type { Metadata } from 'next';
import './globals.css';
import AuthSessionProvider from '@/provider/AuthSessionProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable}`}>
        <QueryProvider>
          <AuthSessionProvider>{children}</AuthSessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
